project:
  type: website
  
format:
  html:
    theme: 
      - litera
      - layout/css/econpol.scss

bibliography: data/lit/wipol_spec.bib
csl: data/lit/wirtschaftsuniversitat-wien-author-date.csl

website:
  title: "PI 2159 Special Topics in Economic Policy"
  site-url: "https://mschnetzer.github.io/econpol/"
  description-meta: "The economics of inequality"
  
  navbar:
    pinned: true
    background: light
    foreground: "#5d8198"
    collapse: true
    right:
      - href: index.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: essayposter.qmd
        text: Essay & Poster
        
  page-footer:
    right: |
      {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by {{< var author >}}
    left: |
      Made with {{< fa heart >}} and {{< fa brands r-project >}} [Quarto](https://quarto.org/)