---
title: "{{< var course.title >}}"
subtitle: "{{< var course.subtitle >}}"
details: |
    {{< var course.number >}} • {{< var course.semester >}} <br> {{< var university.name >}}
course-icon: "fa-scale-unbalanced"
course-icon-bg: "fa-comment"
page-layout: full
format:
  html:
    template-partials: layout/partials/title-block.html
    css: layout/css/econpol.scss
---

::: {.home}

::: {.grid .course-info}

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
#### Lecturer

- {{< fa user >}} &nbsp; {{< var instructor.name >}}
- {{< fa globe >}} &nbsp; [{{< var instructor.url >}}]({{< var instructor.url >}})
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>
- {{< fa brands twitter >}} &nbsp; [{{< var instructor.twitter >}}](https://www.twitter.com/{{< var instructor.twitter >}})
:::

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
#### Course details

- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
:::

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
#### Contact

{{< var instructor.contact_policy >}}
:::

:::


#### Summary

This course covers the triangulation of the distribution of income and wealth, economic growth and wellbeing, and policy making. The starting point is a broad survey of the recent empirical research on the distribution of income and wealth. Hereafter, we will address the nexus between inequality and economic growth from a theoretical and empirical perspective. Finally, students will discuss the linkage between inequality, political power, and policy aspects. All topics are approached with references to recent publications in scientific journals and a policy-relevant focus.

To sum up, students will gain:

::: {.summary-points}
- an overview of the recent empirical research on inequality of income and wealth
- a basic understanding of the theoretical and empirical relationship between inequality and aggregate demand
- a multi-paradigmatic perspective on power relations and policy debates in economics
:::

:::
